// SYNCED COPY — DO NOT EDIT.
// Source: server/proto/service.proto
// Regenerate: cd server && make gen-proto-all

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolService_RegisterTool_FullMethodName      = "/api.ToolService/RegisterTool"
	ToolService_ListTools_FullMethodName         = "/api.ToolService/ListTools"
	ToolService_GetToolById_FullMethodName       = "/api.ToolService/GetToolById"
	ToolService_GetToolByName_FullMethodName     = "/api.ToolService/GetToolByName"
	ToolService_DeleteTool_FullMethodName        = "/api.ToolService/DeleteTool"
	ToolService_UpdateToolPing_FullMethodName    = "/api.ToolService/UpdateToolPing"
	ToolService_StreamExecuteTool_FullMethodName = "/api.ToolService/StreamExecuteTool"
	ToolService_ResumeStream_FullMethodName      = "/api.ToolService/ResumeStream"
	ToolService_ExecuteTool_FullMethodName       = "/api.ToolService/ExecuteTool"
	ToolService_HealthCheck_FullMethodName       = "/api.ToolService/HealthCheck"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ======================
// Tool Service
// ======================
type ToolServiceClient interface {
	// Tool management
	RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error)
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	GetToolById(ctx context.Context, in *GetToolByIdRequest, opts ...grpc.CallOption) (*GetToolResponse, error)
	GetToolByName(ctx context.Context, in *GetToolByNameRequest, opts ...grpc.CallOption) (*GetToolResponse, error)
	DeleteTool(ctx context.Context, in *DeleteToolRequest, opts ...grpc.CallOption) (*DeleteToolResponse, error)
	UpdateToolPing(ctx context.Context, in *UpdateToolPingRequest, opts ...grpc.CallOption) (*Tool, error)
	// Consumer execution entrypoints create request-backed work on the control plane.
	// Request state, claim, and result lifecycle ownership stays in RequestsService.
	StreamExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteToolChunk], error)
	// Resume a broken stream from the last acknowledged sequence number.
	// The server retains a bounded chunk window; if the requested sequence has
	// fallen out of that window, this RPC fails with OUT_OF_RANGE.
	ResumeStream(ctx context.Context, in *ResumeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteToolChunk], error)
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
	// Health check (can be in any service or its own)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterToolResponse)
	err := c.cc.Invoke(ctx, ToolService_RegisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, ToolService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetToolById(ctx context.Context, in *GetToolByIdRequest, opts ...grpc.CallOption) (*GetToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolResponse)
	err := c.cc.Invoke(ctx, ToolService_GetToolById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetToolByName(ctx context.Context, in *GetToolByNameRequest, opts ...grpc.CallOption) (*GetToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolResponse)
	err := c.cc.Invoke(ctx, ToolService_GetToolByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) DeleteTool(ctx context.Context, in *DeleteToolRequest, opts ...grpc.CallOption) (*DeleteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteToolResponse)
	err := c.cc.Invoke(ctx, ToolService_DeleteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) UpdateToolPing(ctx context.Context, in *UpdateToolPingRequest, opts ...grpc.CallOption) (*Tool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tool)
	err := c.cc.Invoke(ctx, ToolService_UpdateToolPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) StreamExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteToolChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolService_ServiceDesc.Streams[0], ToolService_StreamExecuteTool_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteToolRequest, ExecuteToolChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_StreamExecuteToolClient = grpc.ServerStreamingClient[ExecuteToolChunk]

func (c *toolServiceClient) ResumeStream(ctx context.Context, in *ResumeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteToolChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolService_ServiceDesc.Streams[1], ToolService_ResumeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResumeStreamRequest, ExecuteToolChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_ResumeStreamClient = grpc.ServerStreamingClient[ExecuteToolChunk]

func (c *toolServiceClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, ToolService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ToolService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
//
// ======================
// Tool Service
// ======================
type ToolServiceServer interface {
	// Tool management
	RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error)
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	GetToolById(context.Context, *GetToolByIdRequest) (*GetToolResponse, error)
	GetToolByName(context.Context, *GetToolByNameRequest) (*GetToolResponse, error)
	DeleteTool(context.Context, *DeleteToolRequest) (*DeleteToolResponse, error)
	UpdateToolPing(context.Context, *UpdateToolPingRequest) (*Tool, error)
	// Consumer execution entrypoints create request-backed work on the control plane.
	// Request state, claim, and result lifecycle ownership stays in RequestsService.
	StreamExecuteTool(*ExecuteToolRequest, grpc.ServerStreamingServer[ExecuteToolChunk]) error
	// Resume a broken stream from the last acknowledged sequence number.
	// The server retains a bounded chunk window; if the requested sequence has
	// fallen out of that window, this RPC fails with OUT_OF_RANGE.
	ResumeStream(*ResumeStreamRequest, grpc.ServerStreamingServer[ExecuteToolChunk]) error
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	// Health check (can be in any service or its own)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTool not implemented")
}
func (UnimplementedToolServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedToolServiceServer) GetToolById(context.Context, *GetToolByIdRequest) (*GetToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolById not implemented")
}
func (UnimplementedToolServiceServer) GetToolByName(context.Context, *GetToolByNameRequest) (*GetToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolByName not implemented")
}
func (UnimplementedToolServiceServer) DeleteTool(context.Context, *DeleteToolRequest) (*DeleteToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTool not implemented")
}
func (UnimplementedToolServiceServer) UpdateToolPing(context.Context, *UpdateToolPingRequest) (*Tool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateToolPing not implemented")
}
func (UnimplementedToolServiceServer) StreamExecuteTool(*ExecuteToolRequest, grpc.ServerStreamingServer[ExecuteToolChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamExecuteTool not implemented")
}
func (UnimplementedToolServiceServer) ResumeStream(*ResumeStreamRequest, grpc.ServerStreamingServer[ExecuteToolChunk]) error {
	return status.Errorf(codes.Unimplemented, "method ResumeStream not implemented")
}
func (UnimplementedToolServiceServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedToolServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call pancis, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_RegisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).RegisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_RegisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).RegisterTool(ctx, req.(*RegisterToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetToolById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetToolById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetToolById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetToolById(ctx, req.(*GetToolByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetToolByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetToolByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetToolByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetToolByName(ctx, req.(*GetToolByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_DeleteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).DeleteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_DeleteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).DeleteTool(ctx, req.(*DeleteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_UpdateToolPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateToolPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).UpdateToolPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_UpdateToolPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).UpdateToolPing(ctx, req.(*UpdateToolPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_StreamExecuteTool_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteToolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToolServiceServer).StreamExecuteTool(m, &grpc.GenericServerStream[ExecuteToolRequest, ExecuteToolChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_StreamExecuteToolServer = grpc.ServerStreamingServer[ExecuteToolChunk]

func _ToolService_ResumeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResumeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToolServiceServer).ResumeStream(m, &grpc.GenericServerStream[ResumeStreamRequest, ExecuteToolChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_ResumeStreamServer = grpc.ServerStreamingServer[ExecuteToolChunk]

func _ToolService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTool",
			Handler:    _ToolService_RegisterTool_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _ToolService_ListTools_Handler,
		},
		{
			MethodName: "GetToolById",
			Handler:    _ToolService_GetToolById_Handler,
		},
		{
			MethodName: "GetToolByName",
			Handler:    _ToolService_GetToolByName_Handler,
		},
		{
			MethodName: "DeleteTool",
			Handler:    _ToolService_DeleteTool_Handler,
		},
		{
			MethodName: "UpdateToolPing",
			Handler:    _ToolService_UpdateToolPing_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _ToolService_ExecuteTool_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ToolService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExecuteTool",
			Handler:       _ToolService_StreamExecuteTool_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ResumeStream",
			Handler:       _ToolService_ResumeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}

const (
	SessionsService_CreateSession_FullMethodName       = "/api.SessionsService/CreateSession"
	SessionsService_GetSession_FullMethodName          = "/api.SessionsService/GetSession"
	SessionsService_ListSessions_FullMethodName        = "/api.SessionsService/ListSessions"
	SessionsService_UpdateSession_FullMethodName       = "/api.SessionsService/UpdateSession"
	SessionsService_DeleteSession_FullMethodName       = "/api.SessionsService/DeleteSession"
	SessionsService_ListUserSessions_FullMethodName    = "/api.SessionsService/ListUserSessions"
	SessionsService_BulkDeleteSessions_FullMethodName  = "/api.SessionsService/BulkDeleteSessions"
	SessionsService_GetSessionStats_FullMethodName     = "/api.SessionsService/GetSessionStats"
	SessionsService_RefreshSessionToken_FullMethodName = "/api.SessionsService/RefreshSessionToken"
	SessionsService_InvalidateSession_FullMethodName   = "/api.SessionsService/InvalidateSession"
	SessionsService_CreateApiKey_FullMethodName        = "/api.SessionsService/CreateApiKey"
	SessionsService_ListApiKeys_FullMethodName         = "/api.SessionsService/ListApiKeys"
	SessionsService_RevokeApiKey_FullMethodName        = "/api.SessionsService/RevokeApiKey"
)

// SessionsServiceClient is the client API for SessionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ======================
// Session Service
// ======================
type SessionsServiceClient interface {
	// Session management
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// Enhanced session management
	ListUserSessions(ctx context.Context, in *ListUserSessionsRequest, opts ...grpc.CallOption) (*ListUserSessionsResponse, error)
	BulkDeleteSessions(ctx context.Context, in *BulkDeleteSessionsRequest, opts ...grpc.CallOption) (*BulkDeleteSessionsResponse, error)
	GetSessionStats(ctx context.Context, in *GetSessionStatsRequest, opts ...grpc.CallOption) (*GetSessionStatsResponse, error)
	RefreshSessionToken(ctx context.Context, in *RefreshSessionTokenRequest, opts ...grpc.CallOption) (*RefreshSessionTokenResponse, error)
	InvalidateSession(ctx context.Context, in *InvalidateSessionRequest, opts ...grpc.CallOption) (*InvalidateSessionResponse, error)
	// API key management
	CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*ApiKey, error)
	ListApiKeys(ctx context.Context, in *ListApiKeysRequest, opts ...grpc.CallOption) (*ListApiKeysResponse, error)
	RevokeApiKey(ctx context.Context, in *RevokeApiKeyRequest, opts ...grpc.CallOption) (*RevokeApiKeyResponse, error)
}

type sessionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionsServiceClient(cc grpc.ClientConnInterface) SessionsServiceClient {
	return &sessionsServiceClient{cc}
}

func (c *sessionsServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, SessionsService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionsService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionsService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, SessionsService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) ListUserSessions(ctx context.Context, in *ListUserSessionsRequest, opts ...grpc.CallOption) (*ListUserSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserSessionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_ListUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) BulkDeleteSessions(ctx context.Context, in *BulkDeleteSessionsRequest, opts ...grpc.CallOption) (*BulkDeleteSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkDeleteSessionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_BulkDeleteSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) GetSessionStats(ctx context.Context, in *GetSessionStatsRequest, opts ...grpc.CallOption) (*GetSessionStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionStatsResponse)
	err := c.cc.Invoke(ctx, SessionsService_GetSessionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) RefreshSessionToken(ctx context.Context, in *RefreshSessionTokenRequest, opts ...grpc.CallOption) (*RefreshSessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshSessionTokenResponse)
	err := c.cc.Invoke(ctx, SessionsService_RefreshSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) InvalidateSession(ctx context.Context, in *InvalidateSessionRequest, opts ...grpc.CallOption) (*InvalidateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateSessionResponse)
	err := c.cc.Invoke(ctx, SessionsService_InvalidateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*ApiKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKey)
	err := c.cc.Invoke(ctx, SessionsService_CreateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) ListApiKeys(ctx context.Context, in *ListApiKeysRequest, opts ...grpc.CallOption) (*ListApiKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApiKeysResponse)
	err := c.cc.Invoke(ctx, SessionsService_ListApiKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) RevokeApiKey(ctx context.Context, in *RevokeApiKeyRequest, opts ...grpc.CallOption) (*RevokeApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeApiKeyResponse)
	err := c.cc.Invoke(ctx, SessionsService_RevokeApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionsServiceServer is the server API for SessionsService service.
// All implementations must embed UnimplementedSessionsServiceServer
// for forward compatibility.
//
// ======================
// Session Service
// ======================
type SessionsServiceServer interface {
	// Session management
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// Enhanced session management
	ListUserSessions(context.Context, *ListUserSessionsRequest) (*ListUserSessionsResponse, error)
	BulkDeleteSessions(context.Context, *BulkDeleteSessionsRequest) (*BulkDeleteSessionsResponse, error)
	GetSessionStats(context.Context, *GetSessionStatsRequest) (*GetSessionStatsResponse, error)
	RefreshSessionToken(context.Context, *RefreshSessionTokenRequest) (*RefreshSessionTokenResponse, error)
	InvalidateSession(context.Context, *InvalidateSessionRequest) (*InvalidateSessionResponse, error)
	// API key management
	CreateApiKey(context.Context, *CreateApiKeyRequest) (*ApiKey, error)
	ListApiKeys(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error)
	RevokeApiKey(context.Context, *RevokeApiKeyRequest) (*RevokeApiKeyResponse, error)
	mustEmbedUnimplementedSessionsServiceServer()
}

// UnimplementedSessionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionsServiceServer struct{}

func (UnimplementedSessionsServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionsServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionsServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionsServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedSessionsServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedSessionsServiceServer) ListUserSessions(context.Context, *ListUserSessionsRequest) (*ListUserSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserSessions not implemented")
}
func (UnimplementedSessionsServiceServer) BulkDeleteSessions(context.Context, *BulkDeleteSessionsRequest) (*BulkDeleteSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkDeleteSessions not implemented")
}
func (UnimplementedSessionsServiceServer) GetSessionStats(context.Context, *GetSessionStatsRequest) (*GetSessionStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionStats not implemented")
}
func (UnimplementedSessionsServiceServer) RefreshSessionToken(context.Context, *RefreshSessionTokenRequest) (*RefreshSessionTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSessionToken not implemented")
}
func (UnimplementedSessionsServiceServer) InvalidateSession(context.Context, *InvalidateSessionRequest) (*InvalidateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateSession not implemented")
}
func (UnimplementedSessionsServiceServer) CreateApiKey(context.Context, *CreateApiKeyRequest) (*ApiKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApiKey not implemented")
}
func (UnimplementedSessionsServiceServer) ListApiKeys(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApiKeys not implemented")
}
func (UnimplementedSessionsServiceServer) RevokeApiKey(context.Context, *RevokeApiKeyRequest) (*RevokeApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeApiKey not implemented")
}
func (UnimplementedSessionsServiceServer) mustEmbedUnimplementedSessionsServiceServer() {}
func (UnimplementedSessionsServiceServer) testEmbeddedByValue()                         {}

// UnsafeSessionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionsServiceServer will
// result in compilation errors.
type UnsafeSessionsServiceServer interface {
	mustEmbedUnimplementedSessionsServiceServer()
}

func RegisterSessionsServiceServer(s grpc.ServiceRegistrar, srv SessionsServiceServer) {
	// If the following call pancis, it indicates UnimplementedSessionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionsService_ServiceDesc, srv)
}

func _SessionsService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_ListUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).ListUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_ListUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).ListUserSessions(ctx, req.(*ListUserSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_BulkDeleteSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkDeleteSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).BulkDeleteSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_BulkDeleteSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).BulkDeleteSessions(ctx, req.(*BulkDeleteSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_GetSessionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetSessionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetSessionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetSessionStats(ctx, req.(*GetSessionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_RefreshSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).RefreshSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_RefreshSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).RefreshSessionToken(ctx, req.(*RefreshSessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_InvalidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).InvalidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_InvalidateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).InvalidateSession(ctx, req.(*InvalidateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_CreateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).CreateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_CreateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).CreateApiKey(ctx, req.(*CreateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_ListApiKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApiKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).ListApiKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_ListApiKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).ListApiKeys(ctx, req.(*ListApiKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_RevokeApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).RevokeApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_RevokeApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).RevokeApiKey(ctx, req.(*RevokeApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionsService_ServiceDesc is the grpc.ServiceDesc for SessionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.SessionsService",
	HandlerType: (*SessionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _SessionsService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionsService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _SessionsService_ListSessions_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _SessionsService_UpdateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SessionsService_DeleteSession_Handler,
		},
		{
			MethodName: "ListUserSessions",
			Handler:    _SessionsService_ListUserSessions_Handler,
		},
		{
			MethodName: "BulkDeleteSessions",
			Handler:    _SessionsService_BulkDeleteSessions_Handler,
		},
		{
			MethodName: "GetSessionStats",
			Handler:    _SessionsService_GetSessionStats_Handler,
		},
		{
			MethodName: "RefreshSessionToken",
			Handler:    _SessionsService_RefreshSessionToken_Handler,
		},
		{
			MethodName: "InvalidateSession",
			Handler:    _SessionsService_InvalidateSession_Handler,
		},
		{
			MethodName: "CreateApiKey",
			Handler:    _SessionsService_CreateApiKey_Handler,
		},
		{
			MethodName: "ListApiKeys",
			Handler:    _SessionsService_ListApiKeys_Handler,
		},
		{
			MethodName: "RevokeApiKey",
			Handler:    _SessionsService_RevokeApiKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

const (
	MachinesService_RegisterMachine_FullMethodName   = "/api.MachinesService/RegisterMachine"
	MachinesService_ListMachines_FullMethodName      = "/api.MachinesService/ListMachines"
	MachinesService_GetMachine_FullMethodName        = "/api.MachinesService/GetMachine"
	MachinesService_UpdateMachinePing_FullMethodName = "/api.MachinesService/UpdateMachinePing"
	MachinesService_UnregisterMachine_FullMethodName = "/api.MachinesService/UnregisterMachine"
	MachinesService_DrainMachine_FullMethodName      = "/api.MachinesService/DrainMachine"
)

// MachinesServiceClient is the client API for MachinesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ======================
// Machine Service
// ======================
type MachinesServiceClient interface {
	// Machine management
	RegisterMachine(ctx context.Context, in *RegisterMachineRequest, opts ...grpc.CallOption) (*Machine, error)
	ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...grpc.CallOption) (*ListMachinesResponse, error)
	GetMachine(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*Machine, error)
	UpdateMachinePing(ctx context.Context, in *UpdateMachinePingRequest, opts ...grpc.CallOption) (*Machine, error)
	UnregisterMachine(ctx context.Context, in *UnregisterMachineRequest, opts ...grpc.CallOption) (*UnregisterMachineResponse, error)
	// Drain a machine: finish in-flight work then unregister
	DrainMachine(ctx context.Context, in *DrainMachineRequest, opts ...grpc.CallOption) (*DrainMachineResponse, error)
}

type machinesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachinesServiceClient(cc grpc.ClientConnInterface) MachinesServiceClient {
	return &machinesServiceClient{cc}
}

func (c *machinesServiceClient) RegisterMachine(ctx context.Context, in *RegisterMachineRequest, opts ...grpc.CallOption) (*Machine, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Machine)
	err := c.cc.Invoke(ctx, MachinesService_RegisterMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machinesServiceClient) ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...grpc.CallOption) (*ListMachinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMachinesResponse)
	err := c.cc.Invoke(ctx, MachinesService_ListMachines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machinesServiceClient) GetMachine(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*Machine, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Machine)
	err := c.cc.Invoke(ctx, MachinesService_GetMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machinesServiceClient) UpdateMachinePing(ctx context.Context, in *UpdateMachinePingRequest, opts ...grpc.CallOption) (*Machine, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Machine)
	err := c.cc.Invoke(ctx, MachinesService_UpdateMachinePing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machinesServiceClient) UnregisterMachine(ctx context.Context, in *UnregisterMachineRequest, opts ...grpc.CallOption) (*UnregisterMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterMachineResponse)
	err := c.cc.Invoke(ctx, MachinesService_UnregisterMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machinesServiceClient) DrainMachine(ctx context.Context, in *DrainMachineRequest, opts ...grpc.CallOption) (*DrainMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainMachineResponse)
	err := c.cc.Invoke(ctx, MachinesService_DrainMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachinesServiceServer is the server API for MachinesService service.
// All implementations must embed UnimplementedMachinesServiceServer
// for forward compatibility.
//
// ======================
// Machine Service
// ======================
type MachinesServiceServer interface {
	// Machine management
	RegisterMachine(context.Context, *RegisterMachineRequest) (*Machine, error)
	ListMachines(context.Context, *ListMachinesRequest) (*ListMachinesResponse, error)
	GetMachine(context.Context, *GetMachineRequest) (*Machine, error)
	UpdateMachinePing(context.Context, *UpdateMachinePingRequest) (*Machine, error)
	UnregisterMachine(context.Context, *UnregisterMachineRequest) (*UnregisterMachineResponse, error)
	// Drain a machine: finish in-flight work then unregister
	DrainMachine(context.Context, *DrainMachineRequest) (*DrainMachineResponse, error)
	mustEmbedUnimplementedMachinesServiceServer()
}

// UnimplementedMachinesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachinesServiceServer struct{}

func (UnimplementedMachinesServiceServer) RegisterMachine(context.Context, *RegisterMachineRequest) (*Machine, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMachine not implemented")
}
func (UnimplementedMachinesServiceServer) ListMachines(context.Context, *ListMachinesRequest) (*ListMachinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMachines not implemented")
}
func (UnimplementedMachinesServiceServer) GetMachine(context.Context, *GetMachineRequest) (*Machine, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMachine not implemented")
}
func (UnimplementedMachinesServiceServer) UpdateMachinePing(context.Context, *UpdateMachinePingRequest) (*Machine, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMachinePing not implemented")
}
func (UnimplementedMachinesServiceServer) UnregisterMachine(context.Context, *UnregisterMachineRequest) (*UnregisterMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterMachine not implemented")
}
func (UnimplementedMachinesServiceServer) DrainMachine(context.Context, *DrainMachineRequest) (*DrainMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrainMachine not implemented")
}
func (UnimplementedMachinesServiceServer) mustEmbedUnimplementedMachinesServiceServer() {}
func (UnimplementedMachinesServiceServer) testEmbeddedByValue()                         {}

// UnsafeMachinesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachinesServiceServer will
// result in compilation errors.
type UnsafeMachinesServiceServer interface {
	mustEmbedUnimplementedMachinesServiceServer()
}

func RegisterMachinesServiceServer(s grpc.ServiceRegistrar, srv MachinesServiceServer) {
	// If the following call pancis, it indicates UnimplementedMachinesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachinesService_ServiceDesc, srv)
}

func _MachinesService_RegisterMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachinesServiceServer).RegisterMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachinesService_RegisterMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachinesServiceServer).RegisterMachine(ctx, req.(*RegisterMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachinesService_ListMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMachinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachinesServiceServer).ListMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachinesService_ListMachines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachinesServiceServer).ListMachines(ctx, req.(*ListMachinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachinesService_GetMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachinesServiceServer).GetMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachinesService_GetMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachinesServiceServer).GetMachine(ctx, req.(*GetMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachinesService_UpdateMachinePing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMachinePingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachinesServiceServer).UpdateMachinePing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachinesService_UpdateMachinePing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachinesServiceServer).UpdateMachinePing(ctx, req.(*UpdateMachinePingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachinesService_UnregisterMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachinesServiceServer).UnregisterMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachinesService_UnregisterMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachinesServiceServer).UnregisterMachine(ctx, req.(*UnregisterMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachinesService_DrainMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachinesServiceServer).DrainMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachinesService_DrainMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachinesServiceServer).DrainMachine(ctx, req.(*DrainMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachinesService_ServiceDesc is the grpc.ServiceDesc for MachinesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachinesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.MachinesService",
	HandlerType: (*MachinesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterMachine",
			Handler:    _MachinesService_RegisterMachine_Handler,
		},
		{
			MethodName: "ListMachines",
			Handler:    _MachinesService_ListMachines_Handler,
		},
		{
			MethodName: "GetMachine",
			Handler:    _MachinesService_GetMachine_Handler,
		},
		{
			MethodName: "UpdateMachinePing",
			Handler:    _MachinesService_UpdateMachinePing_Handler,
		},
		{
			MethodName: "UnregisterMachine",
			Handler:    _MachinesService_UnregisterMachine_Handler,
		},
		{
			MethodName: "DrainMachine",
			Handler:    _MachinesService_DrainMachine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

const (
	RequestsService_CreateRequest_FullMethodName       = "/api.RequestsService/CreateRequest"
	RequestsService_GetRequest_FullMethodName          = "/api.RequestsService/GetRequest"
	RequestsService_ListRequests_FullMethodName        = "/api.RequestsService/ListRequests"
	RequestsService_UpdateRequest_FullMethodName       = "/api.RequestsService/UpdateRequest"
	RequestsService_ClaimRequest_FullMethodName        = "/api.RequestsService/ClaimRequest"
	RequestsService_CancelRequest_FullMethodName       = "/api.RequestsService/CancelRequest"
	RequestsService_SubmitRequestResult_FullMethodName = "/api.RequestsService/SubmitRequestResult"
	RequestsService_AppendRequestChunks_FullMethodName = "/api.RequestsService/AppendRequestChunks"
	RequestsService_GetRequestChunks_FullMethodName    = "/api.RequestsService/GetRequestChunks"
)

// RequestsServiceClient is the client API for RequestsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ======================
// Request Service
// ======================
type RequestsServiceClient interface {
	// Request management
	CreateRequest(ctx context.Context, in *CreateRequestRequest, opts ...grpc.CallOption) (*Request, error)
	GetRequest(ctx context.Context, in *GetRequestRequest, opts ...grpc.CallOption) (*Request, error)
	ListRequests(ctx context.Context, in *ListRequestsRequest, opts ...grpc.CallOption) (*ListRequestsResponse, error)
	UpdateRequest(ctx context.Context, in *UpdateRequestRequest, opts ...grpc.CallOption) (*Request, error)
	ClaimRequest(ctx context.Context, in *ClaimRequestRequest, opts ...grpc.CallOption) (*Request, error)
	CancelRequest(ctx context.Context, in *CancelRequestRequest, opts ...grpc.CallOption) (*CancelRequestResponse, error)
	SubmitRequestResult(ctx context.Context, in *SubmitRequestResultRequest, opts ...grpc.CallOption) (*SubmitRequestResultResponse, error)
	AppendRequestChunks(ctx context.Context, in *AppendRequestChunksRequest, opts ...grpc.CallOption) (*AppendRequestChunksResponse, error)
	GetRequestChunks(ctx context.Context, in *GetRequestChunksRequest, opts ...grpc.CallOption) (*GetRequestChunksResponse, error)
}

type requestsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestsServiceClient(cc grpc.ClientConnInterface) RequestsServiceClient {
	return &requestsServiceClient{cc}
}

func (c *requestsServiceClient) CreateRequest(ctx context.Context, in *CreateRequestRequest, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, RequestsService_CreateRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestsServiceClient) GetRequest(ctx context.Context, in *GetRequestRequest, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, RequestsService_GetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestsServiceClient) ListRequests(ctx context.Context, in *ListRequestsRequest, opts ...grpc.CallOption) (*ListRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRequestsResponse)
	err := c.cc.Invoke(ctx, RequestsService_ListRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestsServiceClient) UpdateRequest(ctx context.Context, in *UpdateRequestRequest, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, RequestsService_UpdateRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestsServiceClient) ClaimRequest(ctx context.Context, in *ClaimRequestRequest, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, RequestsService_ClaimRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestsServiceClient) CancelRequest(ctx context.Context, in *CancelRequestRequest, opts ...grpc.CallOption) (*CancelRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRequestResponse)
	err := c.cc.Invoke(ctx, RequestsService_CancelRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestsServiceClient) SubmitRequestResult(ctx context.Context, in *SubmitRequestResultRequest, opts ...grpc.CallOption) (*SubmitRequestResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRequestResultResponse)
	err := c.cc.Invoke(ctx, RequestsService_SubmitRequestResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestsServiceClient) AppendRequestChunks(ctx context.Context, in *AppendRequestChunksRequest, opts ...grpc.CallOption) (*AppendRequestChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendRequestChunksResponse)
	err := c.cc.Invoke(ctx, RequestsService_AppendRequestChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestsServiceClient) GetRequestChunks(ctx context.Context, in *GetRequestChunksRequest, opts ...grpc.CallOption) (*GetRequestChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRequestChunksResponse)
	err := c.cc.Invoke(ctx, RequestsService_GetRequestChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestsServiceServer is the server API for RequestsService service.
// All implementations must embed UnimplementedRequestsServiceServer
// for forward compatibility.
//
// ======================
// Request Service
// ======================
type RequestsServiceServer interface {
	// Request management
	CreateRequest(context.Context, *CreateRequestRequest) (*Request, error)
	GetRequest(context.Context, *GetRequestRequest) (*Request, error)
	ListRequests(context.Context, *ListRequestsRequest) (*ListRequestsResponse, error)
	UpdateRequest(context.Context, *UpdateRequestRequest) (*Request, error)
	ClaimRequest(context.Context, *ClaimRequestRequest) (*Request, error)
	CancelRequest(context.Context, *CancelRequestRequest) (*CancelRequestResponse, error)
	SubmitRequestResult(context.Context, *SubmitRequestResultRequest) (*SubmitRequestResultResponse, error)
	AppendRequestChunks(context.Context, *AppendRequestChunksRequest) (*AppendRequestChunksResponse, error)
	GetRequestChunks(context.Context, *GetRequestChunksRequest) (*GetRequestChunksResponse, error)
	mustEmbedUnimplementedRequestsServiceServer()
}

// UnimplementedRequestsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestsServiceServer struct{}

func (UnimplementedRequestsServiceServer) CreateRequest(context.Context, *CreateRequestRequest) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequest not implemented")
}
func (UnimplementedRequestsServiceServer) GetRequest(context.Context, *GetRequestRequest) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedRequestsServiceServer) ListRequests(context.Context, *ListRequestsRequest) (*ListRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequests not implemented")
}
func (UnimplementedRequestsServiceServer) UpdateRequest(context.Context, *UpdateRequestRequest) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequest not implemented")
}
func (UnimplementedRequestsServiceServer) ClaimRequest(context.Context, *ClaimRequestRequest) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimRequest not implemented")
}
func (UnimplementedRequestsServiceServer) CancelRequest(context.Context, *CancelRequestRequest) (*CancelRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRequest not implemented")
}
func (UnimplementedRequestsServiceServer) SubmitRequestResult(context.Context, *SubmitRequestResultRequest) (*SubmitRequestResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRequestResult not implemented")
}
func (UnimplementedRequestsServiceServer) AppendRequestChunks(context.Context, *AppendRequestChunksRequest) (*AppendRequestChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendRequestChunks not implemented")
}
func (UnimplementedRequestsServiceServer) GetRequestChunks(context.Context, *GetRequestChunksRequest) (*GetRequestChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestChunks not implemented")
}
func (UnimplementedRequestsServiceServer) mustEmbedUnimplementedRequestsServiceServer() {}
func (UnimplementedRequestsServiceServer) testEmbeddedByValue()                         {}

// UnsafeRequestsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestsServiceServer will
// result in compilation errors.
type UnsafeRequestsServiceServer interface {
	mustEmbedUnimplementedRequestsServiceServer()
}

func RegisterRequestsServiceServer(s grpc.ServiceRegistrar, srv RequestsServiceServer) {
	// If the following call pancis, it indicates UnimplementedRequestsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestsService_ServiceDesc, srv)
}

func _RequestsService_CreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).CreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_CreateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).CreateRequest(ctx, req.(*CreateRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestsService_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).GetRequest(ctx, req.(*GetRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestsService_ListRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).ListRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_ListRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).ListRequests(ctx, req.(*ListRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestsService_UpdateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).UpdateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_UpdateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).UpdateRequest(ctx, req.(*UpdateRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestsService_ClaimRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).ClaimRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_ClaimRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).ClaimRequest(ctx, req.(*ClaimRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestsService_CancelRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).CancelRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_CancelRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).CancelRequest(ctx, req.(*CancelRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestsService_SubmitRequestResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequestResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).SubmitRequestResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_SubmitRequestResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).SubmitRequestResult(ctx, req.(*SubmitRequestResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestsService_AppendRequestChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequestChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).AppendRequestChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_AppendRequestChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).AppendRequestChunks(ctx, req.(*AppendRequestChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestsService_GetRequestChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestsServiceServer).GetRequestChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestsService_GetRequestChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestsServiceServer).GetRequestChunks(ctx, req.(*GetRequestChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestsService_ServiceDesc is the grpc.ServiceDesc for RequestsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.RequestsService",
	HandlerType: (*RequestsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequest",
			Handler:    _RequestsService_CreateRequest_Handler,
		},
		{
			MethodName: "GetRequest",
			Handler:    _RequestsService_GetRequest_Handler,
		},
		{
			MethodName: "ListRequests",
			Handler:    _RequestsService_ListRequests_Handler,
		},
		{
			MethodName: "UpdateRequest",
			Handler:    _RequestsService_UpdateRequest_Handler,
		},
		{
			MethodName: "ClaimRequest",
			Handler:    _RequestsService_ClaimRequest_Handler,
		},
		{
			MethodName: "CancelRequest",
			Handler:    _RequestsService_CancelRequest_Handler,
		},
		{
			MethodName: "SubmitRequestResult",
			Handler:    _RequestsService_SubmitRequestResult_Handler,
		},
		{
			MethodName: "AppendRequestChunks",
			Handler:    _RequestsService_AppendRequestChunks_Handler,
		},
		{
			MethodName: "GetRequestChunks",
			Handler:    _RequestsService_GetRequestChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

const (
	TasksService_CreateTask_FullMethodName = "/api.TasksService/CreateTask"
	TasksService_GetTask_FullMethodName    = "/api.TasksService/GetTask"
	TasksService_ListTasks_FullMethodName  = "/api.TasksService/ListTasks"
	TasksService_CancelTask_FullMethodName = "/api.TasksService/CancelTask"
)

// TasksServiceClient is the client API for TasksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ======================
// Task Service (Tasks)
// ======================
type TasksServiceClient interface {
	// Task management
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
}

type tasksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTasksServiceClient(cc grpc.ClientConnInterface) TasksServiceClient {
	return &tasksServiceClient{cc}
}

func (c *tasksServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TasksService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TasksService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TasksService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, TasksService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksServiceServer is the server API for TasksService service.
// All implementations must embed UnimplementedTasksServiceServer
// for forward compatibility.
//
// ======================
// Task Service (Tasks)
// ======================
type TasksServiceServer interface {
	// Task management
	CreateTask(context.Context, *CreateTaskRequest) (*Task, error)
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	mustEmbedUnimplementedTasksServiceServer()
}

// UnimplementedTasksServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTasksServiceServer struct{}

func (UnimplementedTasksServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTasksServiceServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTasksServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTasksServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedTasksServiceServer) mustEmbedUnimplementedTasksServiceServer() {}
func (UnimplementedTasksServiceServer) testEmbeddedByValue()                      {}

// UnsafeTasksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TasksServiceServer will
// result in compilation errors.
type UnsafeTasksServiceServer interface {
	mustEmbedUnimplementedTasksServiceServer()
}

func RegisterTasksServiceServer(s grpc.ServiceRegistrar, srv TasksServiceServer) {
	// If the following call pancis, it indicates UnimplementedTasksServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TasksService_ServiceDesc, srv)
}

func _TasksService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TasksService_ServiceDesc is the grpc.ServiceDesc for TasksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TasksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TasksService",
	HandlerType: (*TasksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TasksService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TasksService_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TasksService_ListTasks_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _TasksService_CancelTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
