"""Common functionality shared between gRPC and HTTP Toolplane clients."""

from .base_config import BaseConfig
from .base_connection_manager import BaseConnectionManager
from .base_session_manager import BaseSessionManager
from .base_tool_manager import BaseToolManager
from .constants import (
    BACKPRESSURE_THRESHOLD,
    CACHE_TTL_SECONDS,
    DEFAULT_BUFFER_SIZE,
    DEFAULT_HEARTBEAT_INTERVAL,
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_WORKERS,
    DEFAULT_POLL_INTERVAL,
    DEFAULT_REQUEST_TIMEOUT,
    DEFAULT_RETRY_BACKOFF_MS,
    ERROR_CONNECTION_FAILED,
    ERROR_INVALID_PARAMETERS,
    ERROR_SESSION_NOT_FOUND,
    ERROR_STREAM_INTERRUPTED,
    ERROR_TIMEOUT,
    ERROR_TOOL_NOT_FOUND,
    GRPC_DEFAULT_PORT,
    HTTP_DEFAULT_PORT,
    MAX_DESCRIPTION_LENGTH,
    MAX_SESSION_NAME_LENGTH,
    MAX_TOOL_EXECUTION_TIME,
    MAX_TOOL_NAME_LENGTH,
    STREAM_CHUNK_SIZE,
)
from .utils import (
    TTLCache,
    cache_with_ttl,
    deep_merge,
    extract_host_port,
    format_error_message,
    generate_session_id,
    is_valid_json,
    merge_dicts,
    normalize_url,
    parse_json_safe,
    sanitize_input,
    timeout_wrapper,
    validate_description,
    validate_session_name,
    validate_tool_name,
    with_retry,
)

__all__ = [
    "BaseConfig",
    "BaseToolManager",
    "BaseSessionManager",
    "BaseConnectionManager",
    "generate_session_id",
    "validate_tool_name",
    "validate_session_name",
    "validate_description",
    "parse_json_safe",
    "format_error_message",
    "with_retry",
    "cache_with_ttl",
    "TTLCache",
    "normalize_url",
    "extract_host_port",
    "merge_dicts",
    "sanitize_input",
    "is_valid_json",
    "deep_merge",
    "timeout_wrapper",
    "DEFAULT_HEARTBEAT_INTERVAL",
    "DEFAULT_MAX_WORKERS",
    "DEFAULT_POLL_INTERVAL",
    "DEFAULT_REQUEST_TIMEOUT",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_BUFFER_SIZE",
    "DEFAULT_RETRY_BACKOFF_MS",
    "CACHE_TTL_SECONDS",
    "GRPC_DEFAULT_PORT",
    "HTTP_DEFAULT_PORT",
    "MAX_SESSION_NAME_LENGTH",
    "MAX_TOOL_NAME_LENGTH",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_TOOL_EXECUTION_TIME",
    "STREAM_CHUNK_SIZE",
    "BACKPRESSURE_THRESHOLD",
    "ERROR_CONNECTION_FAILED",
    "ERROR_TOOL_NOT_FOUND",
    "ERROR_SESSION_NOT_FOUND",
    "ERROR_INVALID_PARAMETERS",
    "ERROR_TIMEOUT",
    "ERROR_STREAM_INTERRUPTED",
]
