// Code generated by gen_converters.go; DO NOT EDIT.

package service

import (
	"encoding/json"
	"toolplane/pkg/model"
	proto "toolplane/proto"
	"time"
)

func convertModelToolToProto(in *model.Tool) *proto.Tool {
	if in == nil {
		return nil
	}
	// Convert config
	configMap := make(map[string]string)
	for k, v := range in.Config {
		switch val := v.(type) {
		case string:
			configMap[k] = val
		default:
			if bytes, err := json.Marshal(val); err == nil {
				configMap[k] = string(bytes)
			}
		}
	}
	out := &proto.Tool{
		Id:          in.ID,
		Name:        in.Name,
		Description: in.Description,
		Schema:      in.Schema,
		Config:      configMap,
		CreatedAt:   in.CreatedAt.Format(time.RFC3339),
		LastPingAt:  in.LastPingAt.Format(time.RFC3339),
		SessionId:   in.SessionID,
		Tags:        in.Tags,
	}
	return out
}

func convertModelSessionToProto(in *model.Session) *proto.Session {
	if in == nil {
		return nil
	}
	out := &proto.Session{
		Id:          in.ID,
		Name:        in.Name,
		Description: in.Description,
		CreatedAt:   in.CreatedAt.Format(time.RFC3339),
		CreatedBy:   in.CreatedBy,
		ApiKey:      in.ApiKey,
		Namespace:   in.Namespace,
	}
	return out
}

func convertModelApiKeyToProto(in *model.ApiKey) *proto.ApiKey {
	if in == nil {
		return nil
	}
	var revokedAt string
	if in.RevokedAt != nil {
		revokedAt = in.RevokedAt.Format(time.RFC3339)
	}
	out := &proto.ApiKey{
		Id:        in.ID,
		Name:      in.Name,
		Key:       in.Key,
		SessionId: in.SessionID,
		CreatedAt: in.CreatedAt.Format(time.RFC3339),
		CreatedBy: in.CreatedBy,
		RevokedAt: revokedAt,
	}
	return out
}

func convertModelMachineToProto(in *model.Machine) *proto.Machine {
	if in == nil {
		return nil
	}
	out := &proto.Machine{
		Id:          in.ID,
		SessionId:   in.SessionID,
		SdkVersion:  in.SDKVersion,
		SdkLanguage: in.SDKLanguage,
		Ip:          in.IP,
		CreatedAt:   in.CreatedAt.Format(time.RFC3339),
		LastPingAt:  in.LastPingAt.Format(time.RFC3339),
	}
	return out
}

func convertModelRequestToProto(in *model.Request) *proto.Request {
	if in == nil {
		return nil
	}
	// Convert result
	resultStr := ""
	if in.Result != nil {
		if bytes, err := json.Marshal(in.Result); err == nil {
			resultStr = string(bytes)
		}
	}
	out := &proto.Request{
		Id:                 in.ID,
		SessionId:          in.SessionID,
		ToolName:           in.ToolName,
		Status:             string(in.Status),
		Input:              in.Input,
		Result:             resultStr,
		ResultType:         string(in.ResultType),
		Error:              in.Error,
		CreatedAt:          in.CreatedAt.Format(time.RFC3339),
		UpdatedAt:          in.UpdatedAt.Format(time.RFC3339),
		ExecutingMachineId: in.ExecutingMachineID,
		StreamResults:      in.StreamResults,
	}
	return out
}

func convertModelTaskToProto(in *model.Task) *proto.Task {
	if in == nil {
		return nil
	}
	var completedAt string
	if in.CompletedAt != nil {
		completedAt = in.CompletedAt.Format(time.RFC3339)
	}
	out := &proto.Task{
		Id:          in.ID,
		SessionId:   in.SessionID,
		ToolName:    in.ToolName,
		Status:      string(in.Status),
		Input:       in.Input,
		Result:      in.Result,
		ResultType:  in.ResultType,
		Error:       in.Error,
		CreatedAt:   in.CreatedAt.Format(time.RFC3339),
		UpdatedAt:   in.UpdatedAt.Format(time.RFC3339),
		CompletedAt: completedAt,
	}
	return out
}
