# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_pb2 as proto_dot_service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolServiceStub(object):
    """======================
    Tool Service
    ======================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTool = channel.unary_unary(
                '/api.ToolService/RegisterTool',
                request_serializer=proto_dot_service__pb2.RegisterToolRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.RegisterToolResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/api.ToolService/ListTools',
                request_serializer=proto_dot_service__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.GetToolById = channel.unary_unary(
                '/api.ToolService/GetToolById',
                request_serializer=proto_dot_service__pb2.GetToolByIdRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.GetToolResponse.FromString,
                _registered_method=True)
        self.GetToolByName = channel.unary_unary(
                '/api.ToolService/GetToolByName',
                request_serializer=proto_dot_service__pb2.GetToolByNameRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.GetToolResponse.FromString,
                _registered_method=True)
        self.DeleteTool = channel.unary_unary(
                '/api.ToolService/DeleteTool',
                request_serializer=proto_dot_service__pb2.DeleteToolRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.DeleteToolResponse.FromString,
                _registered_method=True)
        self.UpdateToolPing = channel.unary_unary(
                '/api.ToolService/UpdateToolPing',
                request_serializer=proto_dot_service__pb2.UpdateToolPingRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Tool.FromString,
                _registered_method=True)
        self.StreamExecuteTool = channel.unary_stream(
                '/api.ToolService/StreamExecuteTool',
                request_serializer=proto_dot_service__pb2.ExecuteToolRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ExecuteToolChunk.FromString,
                _registered_method=True)
        self.ResumeStream = channel.unary_stream(
                '/api.ToolService/ResumeStream',
                request_serializer=proto_dot_service__pb2.ResumeStreamRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ExecuteToolChunk.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/api.ToolService/ExecuteTool',
                request_serializer=proto_dot_service__pb2.ExecuteToolRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ExecuteToolResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/api.ToolService/HealthCheck',
                request_serializer=proto_dot_service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ToolServiceServicer(object):
    """======================
    Tool Service
    ======================
    """

    def RegisterTool(self, request, context):
        """Tool management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateToolPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExecuteTool(self, request, context):
        """Consumer execution entrypoints create request-backed work on the control plane.
        Request state, claim, and result lifecycle ownership stays in RequestsService.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeStream(self, request, context):
        """Resume a broken stream from the last acknowledged sequence number.
        The server retains a bounded chunk window; if the requested sequence has
        fallen out of that window, this RPC fails with OUT_OF_RANGE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check (can be in any service or its own)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTool,
                    request_deserializer=proto_dot_service__pb2.RegisterToolRequest.FromString,
                    response_serializer=proto_dot_service__pb2.RegisterToolResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=proto_dot_service__pb2.ListToolsRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListToolsResponse.SerializeToString,
            ),
            'GetToolById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolById,
                    request_deserializer=proto_dot_service__pb2.GetToolByIdRequest.FromString,
                    response_serializer=proto_dot_service__pb2.GetToolResponse.SerializeToString,
            ),
            'GetToolByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolByName,
                    request_deserializer=proto_dot_service__pb2.GetToolByNameRequest.FromString,
                    response_serializer=proto_dot_service__pb2.GetToolResponse.SerializeToString,
            ),
            'DeleteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTool,
                    request_deserializer=proto_dot_service__pb2.DeleteToolRequest.FromString,
                    response_serializer=proto_dot_service__pb2.DeleteToolResponse.SerializeToString,
            ),
            'UpdateToolPing': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateToolPing,
                    request_deserializer=proto_dot_service__pb2.UpdateToolPingRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Tool.SerializeToString,
            ),
            'StreamExecuteTool': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamExecuteTool,
                    request_deserializer=proto_dot_service__pb2.ExecuteToolRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ExecuteToolChunk.SerializeToString,
            ),
            'ResumeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ResumeStream,
                    request_deserializer=proto_dot_service__pb2.ResumeStreamRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ExecuteToolChunk.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=proto_dot_service__pb2.ExecuteToolRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ExecuteToolResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_service__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """======================
    Tool Service
    ======================
    """

    @staticmethod
    def RegisterTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ToolService/RegisterTool',
            proto_dot_service__pb2.RegisterToolRequest.SerializeToString,
            proto_dot_service__pb2.RegisterToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ToolService/ListTools',
            proto_dot_service__pb2.ListToolsRequest.SerializeToString,
            proto_dot_service__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ToolService/GetToolById',
            proto_dot_service__pb2.GetToolByIdRequest.SerializeToString,
            proto_dot_service__pb2.GetToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ToolService/GetToolByName',
            proto_dot_service__pb2.GetToolByNameRequest.SerializeToString,
            proto_dot_service__pb2.GetToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ToolService/DeleteTool',
            proto_dot_service__pb2.DeleteToolRequest.SerializeToString,
            proto_dot_service__pb2.DeleteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateToolPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ToolService/UpdateToolPing',
            proto_dot_service__pb2.UpdateToolPingRequest.SerializeToString,
            proto_dot_service__pb2.Tool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.ToolService/StreamExecuteTool',
            proto_dot_service__pb2.ExecuteToolRequest.SerializeToString,
            proto_dot_service__pb2.ExecuteToolChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.ToolService/ResumeStream',
            proto_dot_service__pb2.ResumeStreamRequest.SerializeToString,
            proto_dot_service__pb2.ExecuteToolChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ToolService/ExecuteTool',
            proto_dot_service__pb2.ExecuteToolRequest.SerializeToString,
            proto_dot_service__pb2.ExecuteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ToolService/HealthCheck',
            proto_dot_service__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SessionsServiceStub(object):
    """======================
    Session Service
    ======================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/api.SessionsService/CreateSession',
                request_serializer=proto_dot_service__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/api.SessionsService/GetSession',
                request_serializer=proto_dot_service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Session.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/api.SessionsService/ListSessions',
                request_serializer=proto_dot_service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/api.SessionsService/UpdateSession',
                request_serializer=proto_dot_service__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Session.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/api.SessionsService/DeleteSession',
                request_serializer=proto_dot_service__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.ListUserSessions = channel.unary_unary(
                '/api.SessionsService/ListUserSessions',
                request_serializer=proto_dot_service__pb2.ListUserSessionsRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListUserSessionsResponse.FromString,
                _registered_method=True)
        self.BulkDeleteSessions = channel.unary_unary(
                '/api.SessionsService/BulkDeleteSessions',
                request_serializer=proto_dot_service__pb2.BulkDeleteSessionsRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.BulkDeleteSessionsResponse.FromString,
                _registered_method=True)
        self.GetSessionStats = channel.unary_unary(
                '/api.SessionsService/GetSessionStats',
                request_serializer=proto_dot_service__pb2.GetSessionStatsRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.GetSessionStatsResponse.FromString,
                _registered_method=True)
        self.RefreshSessionToken = channel.unary_unary(
                '/api.SessionsService/RefreshSessionToken',
                request_serializer=proto_dot_service__pb2.RefreshSessionTokenRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.RefreshSessionTokenResponse.FromString,
                _registered_method=True)
        self.InvalidateSession = channel.unary_unary(
                '/api.SessionsService/InvalidateSession',
                request_serializer=proto_dot_service__pb2.InvalidateSessionRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.InvalidateSessionResponse.FromString,
                _registered_method=True)
        self.CreateApiKey = channel.unary_unary(
                '/api.SessionsService/CreateApiKey',
                request_serializer=proto_dot_service__pb2.CreateApiKeyRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ApiKey.FromString,
                _registered_method=True)
        self.ListApiKeys = channel.unary_unary(
                '/api.SessionsService/ListApiKeys',
                request_serializer=proto_dot_service__pb2.ListApiKeysRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListApiKeysResponse.FromString,
                _registered_method=True)
        self.RevokeApiKey = channel.unary_unary(
                '/api.SessionsService/RevokeApiKey',
                request_serializer=proto_dot_service__pb2.RevokeApiKeyRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.RevokeApiKeyResponse.FromString,
                _registered_method=True)


class SessionsServiceServicer(object):
    """======================
    Session Service
    ======================
    """

    def CreateSession(self, request, context):
        """Session management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserSessions(self, request, context):
        """Enhanced session management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkDeleteSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshSessionToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiKey(self, request, context):
        """API key management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=proto_dot_service__pb2.CreateSessionRequest.FromString,
                    response_serializer=proto_dot_service__pb2.CreateSessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=proto_dot_service__pb2.GetSessionRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Session.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=proto_dot_service__pb2.ListSessionsRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListSessionsResponse.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=proto_dot_service__pb2.UpdateSessionRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Session.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=proto_dot_service__pb2.DeleteSessionRequest.FromString,
                    response_serializer=proto_dot_service__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'ListUserSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserSessions,
                    request_deserializer=proto_dot_service__pb2.ListUserSessionsRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListUserSessionsResponse.SerializeToString,
            ),
            'BulkDeleteSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkDeleteSessions,
                    request_deserializer=proto_dot_service__pb2.BulkDeleteSessionsRequest.FromString,
                    response_serializer=proto_dot_service__pb2.BulkDeleteSessionsResponse.SerializeToString,
            ),
            'GetSessionStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionStats,
                    request_deserializer=proto_dot_service__pb2.GetSessionStatsRequest.FromString,
                    response_serializer=proto_dot_service__pb2.GetSessionStatsResponse.SerializeToString,
            ),
            'RefreshSessionToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshSessionToken,
                    request_deserializer=proto_dot_service__pb2.RefreshSessionTokenRequest.FromString,
                    response_serializer=proto_dot_service__pb2.RefreshSessionTokenResponse.SerializeToString,
            ),
            'InvalidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateSession,
                    request_deserializer=proto_dot_service__pb2.InvalidateSessionRequest.FromString,
                    response_serializer=proto_dot_service__pb2.InvalidateSessionResponse.SerializeToString,
            ),
            'CreateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiKey,
                    request_deserializer=proto_dot_service__pb2.CreateApiKeyRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ApiKey.SerializeToString,
            ),
            'ListApiKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiKeys,
                    request_deserializer=proto_dot_service__pb2.ListApiKeysRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListApiKeysResponse.SerializeToString,
            ),
            'RevokeApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeApiKey,
                    request_deserializer=proto_dot_service__pb2.RevokeApiKeyRequest.FromString,
                    response_serializer=proto_dot_service__pb2.RevokeApiKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.SessionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.SessionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionsService(object):
    """======================
    Session Service
    ======================
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/CreateSession',
            proto_dot_service__pb2.CreateSessionRequest.SerializeToString,
            proto_dot_service__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/GetSession',
            proto_dot_service__pb2.GetSessionRequest.SerializeToString,
            proto_dot_service__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/ListSessions',
            proto_dot_service__pb2.ListSessionsRequest.SerializeToString,
            proto_dot_service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/UpdateSession',
            proto_dot_service__pb2.UpdateSessionRequest.SerializeToString,
            proto_dot_service__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/DeleteSession',
            proto_dot_service__pb2.DeleteSessionRequest.SerializeToString,
            proto_dot_service__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/ListUserSessions',
            proto_dot_service__pb2.ListUserSessionsRequest.SerializeToString,
            proto_dot_service__pb2.ListUserSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkDeleteSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/BulkDeleteSessions',
            proto_dot_service__pb2.BulkDeleteSessionsRequest.SerializeToString,
            proto_dot_service__pb2.BulkDeleteSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/GetSessionStats',
            proto_dot_service__pb2.GetSessionStatsRequest.SerializeToString,
            proto_dot_service__pb2.GetSessionStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshSessionToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/RefreshSessionToken',
            proto_dot_service__pb2.RefreshSessionTokenRequest.SerializeToString,
            proto_dot_service__pb2.RefreshSessionTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/InvalidateSession',
            proto_dot_service__pb2.InvalidateSessionRequest.SerializeToString,
            proto_dot_service__pb2.InvalidateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/CreateApiKey',
            proto_dot_service__pb2.CreateApiKeyRequest.SerializeToString,
            proto_dot_service__pb2.ApiKey.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApiKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/ListApiKeys',
            proto_dot_service__pb2.ListApiKeysRequest.SerializeToString,
            proto_dot_service__pb2.ListApiKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SessionsService/RevokeApiKey',
            proto_dot_service__pb2.RevokeApiKeyRequest.SerializeToString,
            proto_dot_service__pb2.RevokeApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MachinesServiceStub(object):
    """======================
    Machine Service
    ======================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterMachine = channel.unary_unary(
                '/api.MachinesService/RegisterMachine',
                request_serializer=proto_dot_service__pb2.RegisterMachineRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Machine.FromString,
                _registered_method=True)
        self.ListMachines = channel.unary_unary(
                '/api.MachinesService/ListMachines',
                request_serializer=proto_dot_service__pb2.ListMachinesRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListMachinesResponse.FromString,
                _registered_method=True)
        self.GetMachine = channel.unary_unary(
                '/api.MachinesService/GetMachine',
                request_serializer=proto_dot_service__pb2.GetMachineRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Machine.FromString,
                _registered_method=True)
        self.UpdateMachinePing = channel.unary_unary(
                '/api.MachinesService/UpdateMachinePing',
                request_serializer=proto_dot_service__pb2.UpdateMachinePingRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Machine.FromString,
                _registered_method=True)
        self.UnregisterMachine = channel.unary_unary(
                '/api.MachinesService/UnregisterMachine',
                request_serializer=proto_dot_service__pb2.UnregisterMachineRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.UnregisterMachineResponse.FromString,
                _registered_method=True)
        self.DrainMachine = channel.unary_unary(
                '/api.MachinesService/DrainMachine',
                request_serializer=proto_dot_service__pb2.DrainMachineRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.DrainMachineResponse.FromString,
                _registered_method=True)


class MachinesServiceServicer(object):
    """======================
    Machine Service
    ======================
    """

    def RegisterMachine(self, request, context):
        """Machine management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMachines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMachinePing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterMachine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainMachine(self, request, context):
        """Drain a machine: finish in-flight work then unregister
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MachinesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterMachine,
                    request_deserializer=proto_dot_service__pb2.RegisterMachineRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Machine.SerializeToString,
            ),
            'ListMachines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMachines,
                    request_deserializer=proto_dot_service__pb2.ListMachinesRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListMachinesResponse.SerializeToString,
            ),
            'GetMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachine,
                    request_deserializer=proto_dot_service__pb2.GetMachineRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Machine.SerializeToString,
            ),
            'UpdateMachinePing': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMachinePing,
                    request_deserializer=proto_dot_service__pb2.UpdateMachinePingRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Machine.SerializeToString,
            ),
            'UnregisterMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterMachine,
                    request_deserializer=proto_dot_service__pb2.UnregisterMachineRequest.FromString,
                    response_serializer=proto_dot_service__pb2.UnregisterMachineResponse.SerializeToString,
            ),
            'DrainMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainMachine,
                    request_deserializer=proto_dot_service__pb2.DrainMachineRequest.FromString,
                    response_serializer=proto_dot_service__pb2.DrainMachineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.MachinesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.MachinesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MachinesService(object):
    """======================
    Machine Service
    ======================
    """

    @staticmethod
    def RegisterMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.MachinesService/RegisterMachine',
            proto_dot_service__pb2.RegisterMachineRequest.SerializeToString,
            proto_dot_service__pb2.Machine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMachines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.MachinesService/ListMachines',
            proto_dot_service__pb2.ListMachinesRequest.SerializeToString,
            proto_dot_service__pb2.ListMachinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.MachinesService/GetMachine',
            proto_dot_service__pb2.GetMachineRequest.SerializeToString,
            proto_dot_service__pb2.Machine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMachinePing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.MachinesService/UpdateMachinePing',
            proto_dot_service__pb2.UpdateMachinePingRequest.SerializeToString,
            proto_dot_service__pb2.Machine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.MachinesService/UnregisterMachine',
            proto_dot_service__pb2.UnregisterMachineRequest.SerializeToString,
            proto_dot_service__pb2.UnregisterMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.MachinesService/DrainMachine',
            proto_dot_service__pb2.DrainMachineRequest.SerializeToString,
            proto_dot_service__pb2.DrainMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RequestsServiceStub(object):
    """======================
    Request Service
    ======================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRequest = channel.unary_unary(
                '/api.RequestsService/CreateRequest',
                request_serializer=proto_dot_service__pb2.CreateRequestRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Request.FromString,
                _registered_method=True)
        self.GetRequest = channel.unary_unary(
                '/api.RequestsService/GetRequest',
                request_serializer=proto_dot_service__pb2.GetRequestRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Request.FromString,
                _registered_method=True)
        self.ListRequests = channel.unary_unary(
                '/api.RequestsService/ListRequests',
                request_serializer=proto_dot_service__pb2.ListRequestsRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListRequestsResponse.FromString,
                _registered_method=True)
        self.UpdateRequest = channel.unary_unary(
                '/api.RequestsService/UpdateRequest',
                request_serializer=proto_dot_service__pb2.UpdateRequestRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Request.FromString,
                _registered_method=True)
        self.ClaimRequest = channel.unary_unary(
                '/api.RequestsService/ClaimRequest',
                request_serializer=proto_dot_service__pb2.ClaimRequestRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Request.FromString,
                _registered_method=True)
        self.CancelRequest = channel.unary_unary(
                '/api.RequestsService/CancelRequest',
                request_serializer=proto_dot_service__pb2.CancelRequestRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.CancelRequestResponse.FromString,
                _registered_method=True)
        self.SubmitRequestResult = channel.unary_unary(
                '/api.RequestsService/SubmitRequestResult',
                request_serializer=proto_dot_service__pb2.SubmitRequestResultRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.SubmitRequestResultResponse.FromString,
                _registered_method=True)
        self.AppendRequestChunks = channel.unary_unary(
                '/api.RequestsService/AppendRequestChunks',
                request_serializer=proto_dot_service__pb2.AppendRequestChunksRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.AppendRequestChunksResponse.FromString,
                _registered_method=True)
        self.GetRequestChunks = channel.unary_unary(
                '/api.RequestsService/GetRequestChunks',
                request_serializer=proto_dot_service__pb2.GetRequestChunksRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.GetRequestChunksResponse.FromString,
                _registered_method=True)


class RequestsServiceServicer(object):
    """======================
    Request Service
    ======================
    """

    def CreateRequest(self, request, context):
        """Request management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitRequestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendRequestChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRequestChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RequestsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRequest,
                    request_deserializer=proto_dot_service__pb2.CreateRequestRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Request.SerializeToString,
            ),
            'GetRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRequest,
                    request_deserializer=proto_dot_service__pb2.GetRequestRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Request.SerializeToString,
            ),
            'ListRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRequests,
                    request_deserializer=proto_dot_service__pb2.ListRequestsRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListRequestsResponse.SerializeToString,
            ),
            'UpdateRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRequest,
                    request_deserializer=proto_dot_service__pb2.UpdateRequestRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Request.SerializeToString,
            ),
            'ClaimRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimRequest,
                    request_deserializer=proto_dot_service__pb2.ClaimRequestRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Request.SerializeToString,
            ),
            'CancelRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRequest,
                    request_deserializer=proto_dot_service__pb2.CancelRequestRequest.FromString,
                    response_serializer=proto_dot_service__pb2.CancelRequestResponse.SerializeToString,
            ),
            'SubmitRequestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRequestResult,
                    request_deserializer=proto_dot_service__pb2.SubmitRequestResultRequest.FromString,
                    response_serializer=proto_dot_service__pb2.SubmitRequestResultResponse.SerializeToString,
            ),
            'AppendRequestChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendRequestChunks,
                    request_deserializer=proto_dot_service__pb2.AppendRequestChunksRequest.FromString,
                    response_serializer=proto_dot_service__pb2.AppendRequestChunksResponse.SerializeToString,
            ),
            'GetRequestChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRequestChunks,
                    request_deserializer=proto_dot_service__pb2.GetRequestChunksRequest.FromString,
                    response_serializer=proto_dot_service__pb2.GetRequestChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.RequestsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.RequestsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RequestsService(object):
    """======================
    Request Service
    ======================
    """

    @staticmethod
    def CreateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/CreateRequest',
            proto_dot_service__pb2.CreateRequestRequest.SerializeToString,
            proto_dot_service__pb2.Request.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/GetRequest',
            proto_dot_service__pb2.GetRequestRequest.SerializeToString,
            proto_dot_service__pb2.Request.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/ListRequests',
            proto_dot_service__pb2.ListRequestsRequest.SerializeToString,
            proto_dot_service__pb2.ListRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/UpdateRequest',
            proto_dot_service__pb2.UpdateRequestRequest.SerializeToString,
            proto_dot_service__pb2.Request.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/ClaimRequest',
            proto_dot_service__pb2.ClaimRequestRequest.SerializeToString,
            proto_dot_service__pb2.Request.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/CancelRequest',
            proto_dot_service__pb2.CancelRequestRequest.SerializeToString,
            proto_dot_service__pb2.CancelRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitRequestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/SubmitRequestResult',
            proto_dot_service__pb2.SubmitRequestResultRequest.SerializeToString,
            proto_dot_service__pb2.SubmitRequestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendRequestChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/AppendRequestChunks',
            proto_dot_service__pb2.AppendRequestChunksRequest.SerializeToString,
            proto_dot_service__pb2.AppendRequestChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRequestChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.RequestsService/GetRequestChunks',
            proto_dot_service__pb2.GetRequestChunksRequest.SerializeToString,
            proto_dot_service__pb2.GetRequestChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TasksServiceStub(object):
    """======================
    Task Service (Tasks)
    ======================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/api.TasksService/CreateTask',
                request_serializer=proto_dot_service__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Task.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/api.TasksService/GetTask',
                request_serializer=proto_dot_service__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Task.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/api.TasksService/ListTasks',
                request_serializer=proto_dot_service__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/api.TasksService/CancelTask',
                request_serializer=proto_dot_service__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.CancelTaskResponse.FromString,
                _registered_method=True)


class TasksServiceServicer(object):
    """======================
    Task Service (Tasks)
    ======================
    """

    def CreateTask(self, request, context):
        """Task management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TasksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=proto_dot_service__pb2.CreateTaskRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Task.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=proto_dot_service__pb2.GetTaskRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Task.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=proto_dot_service__pb2.ListTasksRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListTasksResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=proto_dot_service__pb2.CancelTaskRequest.FromString,
                    response_serializer=proto_dot_service__pb2.CancelTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.TasksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.TasksService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TasksService(object):
    """======================
    Task Service (Tasks)
    ======================
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.TasksService/CreateTask',
            proto_dot_service__pb2.CreateTaskRequest.SerializeToString,
            proto_dot_service__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.TasksService/GetTask',
            proto_dot_service__pb2.GetTaskRequest.SerializeToString,
            proto_dot_service__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.TasksService/ListTasks',
            proto_dot_service__pb2.ListTasksRequest.SerializeToString,
            proto_dot_service__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.TasksService/CancelTask',
            proto_dot_service__pb2.CancelTaskRequest.SerializeToString,
            proto_dot_service__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
